### PR TITLE
A proposal that reactions be handled as annotated OBMols rather than OBReactions

### PR DESCRIPTION
**Pull request by baoilleach**
For a viewable version of this see https://github.com/baoilleach/enhancement-proposals/blob/reactions-as-mols/reactions-as-obmols/reaction-handling.md

### CODE REVIEW

**Comment by dkoes** [comment]
DISCLAIMER: Just throwing out ideas here..

How is reaction-specific functionality going to be handled? Through a separate class that provides the methods but does not store the data?  I'm thinking of GetReactant, GetProduct, etc.

What about making OBReaction inherit from OBMol?  The additional state and functionality needed to support reactions would be in this class (as opposed to being added to every atom/mol).

Personally, I find it conceptually easier to think of reactions as collections of individual molecules.  It is certainly common to want to work with reaction components as discrete objects. Perhaps reaction components should not be shared pointers, but instead by copied into the reaction object (and fully owned by the reaction object).

I've used RDKit every time I've had to do something with reactions.  Looking at the OB implementation, I'm reminded why - reactions aren't a transformative object (i.e., you can't apply the reaction).  It might be good to think about how to best support some future API that matches RDKit's capabilities.  Should there be a difference between a reaction "molecule" (containing fully instantiated molecules) and a reaction "pattern" (used to perform chemical transformations)?

**Comment by baoilleach** [comment]
Regarding GetReactant, etc., it's exactly as you say - a facade class (if that's the right term). There's a bit about that in the write-up.

Regarding changing the inheritance, that's an interesting idea, but has all of the same issues that this proposal is trying to address. Well, getting rid of shared_ptr would solve one of the problems. I did propose that earlier (https://github.com/openbabel/enhancement-proposals/pull/5), which led to the discussion that we're having now I guess.

Reaction transformation code would be great - however I do think of this as a separate concept from reaction themselves. However, there are some nice features of having query molecules to represent substructure queries, and reaction transformation "reactions" to represent reaction patterns. For example, you can use the same reader/writer/depictor in theory.

**Comment by baoilleach** [comment]
The 1-month bump.

**Comment by ghutchis** [comment]
I'm good at this point. I'm sold on the idea, and it doesn't seem like there are any meaningful objections beyond "we all want real reaction transformations implemented."

**Pull request merged**
