### PR TITLE
Improve performance of element handling

### PR DESCRIPTION
**Pull request by baoilleach**
See nicely formatted version of text at https://github.com/baoilleach/enhancement-proposals/blob/element_handling/element_handling/element_handling.md

### CODE REVIEW

**Comment by ghutchis** [comment]
Yes, this is totally fine. Go for it!

**Comment by baoilleach** [comment]
Am a bit unsure about the corrected radii. Feels like a hand-wavy approx rather than a real property. So I'm thinking about moving it out to where it's being used.

**Comment by ghutchis** [comment]
I can't remember where it's used anymore. I think it was for estimating bond lengths? It may also have been used for bond order perception.

But an inline helper function is probably sufficient.

**Comment by baoilleach** [comment]
This is generally how it looks: https://github.com/baoilleach/openbabel/commit/5e869499182d4029dbe49eabfb7c6865d6a615a9

I'll start replacing usages of OBElementTable now...

**Comment by ghutchis** [comment]
I think people might be interested in some benchmarks (e.g., how does parsing SDF or PDB file change)?

**Comment by baoilleach** [comment]
I haven't yet ported existing code over but when done, I'll look into it - my guess is that the improvement in speed of SDF parsing will be minimal, if measurable. Similar inefficiencies will exist in the parser itself (I'm guessing) but I want to address fixes that require API changes first.

**Comment by ghutchis** [comment]
Is this now finished? Can we close it as "done"?

**Comment by baoilleach** [comment]
It is done.

**Comment by ghutchis** [comment]
I actually think I should merge this, so we have a record of "successful plans" - what do you think?

**Comment by baoilleach** [comment]
Sure - the only catch is that during the implementation a simpler strategy
can present itself, so that the record here just describes the motivation
and not the eventual implementation detail. Not that there's anything wrong
with that.

- Noel

**Pull request merged**
