### PR TITLE
Reaction handling proposal

### PR DESCRIPTION
**Pull request by baoilleach**
For details see:

https://github.com/baoilleach/enhancement-proposals/blob/reaction_handling/reaction-handling/reaction-handling.md

### CODE REVIEW

**Comment by chrismorl** [comment]
I agree that agents should be treated in the same way as reactions and products, but I'm doubtful about changing what this is.

Some branches of chemistry use mechanisms with multiple reactions undergone by multiple molecules and manipulate these reactions and molecules. The sharing of molecules between reactions mean that, if OBMols were made simply by new OBMol and referred to by OBMol*,  some additional way of deleting them when no longer used would be needed. Using shared_ptr does this transparently, and it would be a pity to abandon it. An ordinary pointer is available using shared_ptr<OBMol> get(), which would maybe work if the other language bindings could access it in some way.

I don't know what an overlay of OBMol is, but why won't the original C++ way of inheritance from OBBase work?

**Comment by baoilleach** [comment]
With SWIG, it's possible to use it from Python but only by making every single OBMol* a shared_ptr. This caused other problems (I'd have to search back through the emails for the details) as might be expected. In short, no matter the theoretical advantages, in practical terms it's a roadblock for the majority of users. As you say, if this is changed then the memory will need to be managed differently. Probably OBReactions will have to always delete them on destruction, and it will be left to user to ensure that this is a safe operation (e.g. by providing copies if they want to keep the original).

By overlay I just meant an annotation (like an SGroup in MDL Molfile terminology) applied to existing atoms in a molecule. For example, some atoms would be annotated as Reactant1, others as Product1. The advantage is that separate readers and writers are not required for reaction formats, that is, the smiles reader/writer could handle reaction smiles; all existing methods that handle OBMol would transparently handle reactions (e.g. SMARTS matcher, depictor).

**Comment by baoilleach** [comment]
(Reopening, as I think Chris closed it in error)

**Comment by baoilleach** [comment]
Would it be good to discuss this over Skype? I am keen to sort this out, and it's no harm to chat anyway. For example, it would be good to discuss the use case you describe. There are various halfway houses that are possible, e.g. have an optional parameter for AddReagent that told the OBReaction who owned the OBMol object (i.e. whether to call the destructor or not). This would still save the memory in your use case.

**Comment by ghutchis** [comment]
I like the overlay use case (e.g., formats can handle reactions). I'm game to chat.. my schedule is online (http://doodle.com/geoffhutchison) but I can also find out-of-work time that matches UK timing.

**Comment by ghutchis** [comment]
At the least, I'd like to discuss whether this particular plan should get pushed back to a 2.6 release so we can get 2.5 out the door.

**Comment by ghutchis** [comment]
@baoilleach - I think we can close this one, right?

**Comment by baoilleach** [comment]
Sure.

**Pull request closed without merging**
